// Code generated by Slice Machine. DO NOT EDIT.

import type * as prismicT from "@prismicio/types";
import type * as prismic from "@prismicio/client";

type Simplify<T> = {
    [KeyType in keyof T]: T[KeyType];
};
/** Content for Home Page documents */
interface HomePageDocumentData {
    /**
     * Slice Zone field in *Home Page*
     *
     * - **Field Type**: Slice Zone
     * - **Placeholder**: *None*
     * - **API ID Path**: home_page.slices[]
     * - **Tab**: Main
     * - **Documentation**: https://prismic.io/docs/core-concepts/slices
     *
     */
    slices: prismicT.SliceZone<HomePageDocumentDataSlicesSlice>;
}
/**
 * Slice for *Home Page → Slice Zone*
 *
 */
type HomePageDocumentDataSlicesSlice = FinalSliceSlice;
/**
 * Home Page document from Prismic
 *
 * - **API ID**: `home_page`
 * - **Repeatable**: `false`
 * - **Documentation**: https://prismic.io/docs/core-concepts/custom-types
 *
 * @typeParam Lang - Language API ID of the document.
 */
export type HomePageDocument<Lang extends string = string> = prismicT.PrismicDocumentWithoutUID<Simplify<HomePageDocumentData>, "home_page", Lang>;
export type AllDocumentTypes = HomePageDocument;
/**
 * Primary content in FinalSlice → Primary
 *
 */
interface FinalSliceSliceDefaultPrimary {
    /**
     * Title field in *FinalSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: final_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Default variation for FinalSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `FinalSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FinalSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<FinalSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *FinalSlice*
 *
 */
type FinalSliceSliceVariation = FinalSliceSliceDefault;
/**
 * FinalSlice Shared Slice
 *
 * - **API ID**: `final_slice`
 * - **Description**: `FinalSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type FinalSliceSlice = prismicT.SharedSlice<"final_slice", FinalSliceSliceVariation>;
/**
 * Primary content in NewFinalSlice → Primary
 *
 */
interface NewFinalSliceSliceDefaultPrimary {
    /**
     * Title field in *NewFinalSlice → Primary*
     *
     * - **Field Type**: Title
     * - **Placeholder**: This is where it all begins...
     * - **API ID Path**: new_final_slice.primary.title
     * - **Documentation**: https://prismic.io/docs/core-concepts/rich-text-title
     *
     */
    title: prismicT.TitleField;
}
/**
 * Default variation for NewFinalSlice Slice
 *
 * - **API ID**: `default`
 * - **Description**: `NewFinalSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NewFinalSliceSliceDefault = prismicT.SharedSliceVariation<"default", Simplify<NewFinalSliceSliceDefaultPrimary>, never>;
/**
 * Slice variation for *NewFinalSlice*
 *
 */
type NewFinalSliceSliceVariation = NewFinalSliceSliceDefault;
/**
 * NewFinalSlice Shared Slice
 *
 * - **API ID**: `new_final_slice`
 * - **Description**: `NewFinalSlice`
 * - **Documentation**: https://prismic.io/docs/core-concepts/reusing-slices
 *
 */
export type NewFinalSliceSlice = prismicT.SharedSlice<"new_final_slice", NewFinalSliceSliceVariation>;
declare module "@prismicio/client" {
    interface CreateClient {
        (repositoryNameOrEndpoint: string, options?: prismic.ClientConfig): prismic.Client<AllDocumentTypes>;
    }
    namespace Content {
        export type { HomePageDocumentData, HomePageDocumentDataSlicesSlice, HomePageDocument, AllDocumentTypes, FinalSliceSliceDefaultPrimary, FinalSliceSliceDefault, FinalSliceSliceVariation, FinalSliceSlice, NewFinalSliceSliceDefaultPrimary, NewFinalSliceSliceDefault, NewFinalSliceSliceVariation, NewFinalSliceSlice };
    }
}
