// Code generated by Slice Machine. DO NOT EDIT.

import FinalSlice from './FinalSlice';
import NewFinalSlice from './NewFinalSlice';

export {
	FinalSlice,
	NewFinalSlice,
};

export const components = {
	final_slice: FinalSlice,
	new_final_slice: NewFinalSlice,
};
