// Code generated by Slice Machine. DO NOT EDIT.

import Features from './Features';
import Form from './Form';
import Hero from './Hero';
import LogoCloud from './LogoCloud';
import Pricing from './Pricing';

export {
	Features,
	Form,
	Hero,
	LogoCloud,
	Pricing,
};

export const components = {
	features: Features,
	form: Form,
	hero: Hero,
	logo_cloud: LogoCloud,
	pricing: Pricing,
};
