// Code generated by Slice Machine. DO NOT EDIT.

import Hero from './Hero';
import LogoCloud from './LogoCloud';

export {
	Hero,
	LogoCloud,
};

export const components = {
	hero: Hero,
	logo_cloud: LogoCloud,
};
