// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  text: dynamic(() => import("./Text")),
  highlighted_text: dynamic(() => import("./HighlightedText")),
};
