import Head from "next/head";
import type { GetStaticPropsContext, InferGetStaticPropsType } from "next";
import { createClient } from "../prismicio";
import { Content } from "@prismicio/client";
import { SliceZone } from "@prismicio/react";
import { components } from "@/slices";
import { Header } from "@/components/Header";

type HomePageProps = InferGetStaticPropsType<typeof getStaticProps>;

export default function Home({ page, header }: HomePageProps) {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main>
        <Header {...header.data}/>
        <SliceZone slices={page.data.slices} components={components} />
      </main>
    </>
  );
}

export async function getStaticProps({ previewData }: GetStaticPropsContext) {
  const client = createClient({ previewData });
  //    ^ Automatically contains references to document types

  const page = await client.getSingle<Content.HomePageDocument>("home_page");
  //    ^ Typed as HomePageDocument

  const header = await client.getSingle<Content.HeaderDocument>("header");
  //    ^ Typed as HeaderDocument

  return {
    props: {
      page,
      header
    },
  };
}
