// Code generated by Slice Machine. DO NOT EDIT.

import dynamic from "next/dynamic";

export const components = {
  article_list: dynamic(() => import("./ArticleList")),
  call_to_action: dynamic(() => import("./CallToAction")),
  faq: dynamic(() => import("./Faq")),
  featured_websites_list: dynamic(() => import("./FeaturedWebsitesList")),
  features: dynamic(() => import("./Features")),
  form: dynamic(() => import("./Form")),
  hero: dynamic(() => import("./Hero")),
  job_list: dynamic(() => import("./JobList")),
  logo_cloud: dynamic(() => import("./LogoCloud")),
  pricing: dynamic(() => import("./Pricing")),
  testimonials: dynamic(() => import("./Testimonials")),
};
