// Code generated by Slice Machine. DO NOT EDIT.

import ArticleList from './ArticleList';
import CallToAction from './CallToAction';
import Faq from './Faq';
import Features from './Features';
import Form from './Form';
import Hero from './Hero';
import HighlightedText from './HighlightedText';
import LogoCloud from './LogoCloud';
import Pricing from './Pricing';
import Testimonials from './Testimonials';

export {
	ArticleList,
	CallToAction,
	Faq,
	Features,
	Form,
	Hero,
	HighlightedText,
	LogoCloud,
	Pricing,
	Testimonials,
};

export const components = {
	article_list: ArticleList,
	call_to_action: CallToAction,
	faq: Faq,
	features: Features,
	form: Form,
	hero: Hero,
	highlighted_text: HighlightedText,
	logo_cloud: LogoCloud,
	pricing: Pricing,
	testimonials: Testimonials,
};
